transactions-retained: 2000
migration-enabled: false
debug: false
redis-uri: "redis://localhost:6379/0?timeout=20s&clientName=RedisEconomy"
redis-connection-timeout: 3000 #milliseconds
lang:
  no-console: "<red>You must be in-game to use this command!</red>"
  no-permission: "<red>You do not have permission to use this command!</red>"
  player-not-found: "<red>Player not found!</red>"
  invalid-amount: "<red>Invalid amount!"
  invalid-currency: "<red>Invalid currency!"
  insufficient-funds: "<red>You do not have enough money!</red>"
  balance: "<green>You have %balance%!</green>"
  balance-set: "<green>You set %player% account to %balance% !</green>"
  balance-other: "<green>%player% has %balance% !</green>"
  balance-top: "<green>Top richest players:</green><br>%prevpage%      %page%      %nextpage%"
  balance-top-format: "<aqua>%pos% - %player% %balance%</aqua>"
  pay-self: "<red>You cannot pay yourself!</red>"
  pay-success: "<green>You paid %player% %amount% with %tax_percentage% %tax_applied% of transaction fee!</green>"
  pay-fail: "<red>Pay failed!</red>"
  pay-received: "<green>You received %amount% from %player%!</green>"
  purge-user-success: "<green>Users matching %player% have been purged!</green>"
  switch-currency-success: "<green>Switched %currency% to %switch-currency%.<br>Please restart immediately every instance<br> with RedisEconomy installed to avoid any overwrite!</green>"
  transaction-item:
    outgoing-funds: "<aqua>%timestamp%</aqua> <click:run_command:/transaction %account-owner% %afterbefore%><dark_green>%account-owner%</dark_green></click> -> <click:run_command:/transaction %other-account% %afterbefore%><green>%other-account%</green></click> Change: %amount%%symbol%<br><yellow>Reason: </yellow>%reason%"
    incoming-funds: "<aqua>%timestamp%</aqua> <click:run_command:/transaction %other-account% %afterbefore%><green>%other-account%</green></click> -> <click:run_command:/transaction %account-owner% %afterbefore%><dark_green>%account-owner%</dark_green></click> Change: %amount%%symbol%<br><yellow>Reason: </yellow>%reason%"
  unit-symbols:
    thousands: "k"
    millions: "m"
    billions: "b"
    trillions: "t"
currencies:
  vault:
    currency-single: "$"
    currency-plural: "$"
    starting-balance: 0
    pay-tax: 0
  zircon:
    currency-single: "z"
    currency-plural: "zs"
    starting-balance: 0
    pay-tax: 0
