transactions-retained: 200
migration-enabled: false
debug: false
redis-url: "redis://localhost:6379/0?timeout=10s&clientName=RedisEconomy"
lang:
  no-console: "<red>You must be in-game to use this command!</red>"
  no-permission: "<red>You do not have permission to use this command!</red>"
  player-not-found: "<red>Player not found!</red>"
  invalid-amount: "<red>Invalid amount!<"
  insufficient-funds: "<red>You do not have enough money!</red>"
  balance: "<green>You have %balance%!</green>"
  balance-set: "<green>You set %player% account to %balance% !</green>"
  balance-other: "<green>%player% has %balance% !</green>"
  balance-top: "<green>Top richest players:</green><br>%prevpage%      %page%      %nextpage%"
  balance-top-format: "<aqua>%pos% - %player% %balance%</aqua>"
  pay-self: "<red>You cannot pay yourself!</red>"
  pay-success: "<green>You paid %player% %amount% with %tax_percentage% %tax_applied% of transaction fee!</green>"
  pay-fail: "<red>Pay failed!</red>"
  pay-received: "<green>You received %amount% from %player%!</green>"
  transaction-item: "<aqua>%timestamp%</aqua> <click:run_command:/transaction %sender% %afterbefore%><dark_green>%sender%</dark_green></click> -> <click:run_command:/transaction %receiver% %afterbefore%><green>%receiver%<green></click> %amount%!"
currencies:
  vault:
    currency-single: "dollar"
    currency-plural: "dollars"
    starting-balance: 0
    pay-tax: 0
  zircon:
    currency-single: "zircon"
    currency-plural: "zircons"
    starting-balance: 0
    pay-tax: 0
