name: RedisEconomy
version: '${version}'
api-version: '1.17'
main: dev.unnm3d.rediseconomy.RedisEconomyPlugin
author: Unnm3d
load: STARTUP
depend:
  - Vault
libraries:
  - io.lettuce:lettuce-core:6.7.1.RELEASE
softdepend:
  - PlaceholderAPI
  - Essentials
  - EssentialsX
  - XConomy
  - CMI
  - EconomyPlus
  - BetterEconomy
  - ArcaneEconomy
  - EasyConomy
  - Towny
folia-supported: true
commands:
  pay:
    description: Pay a player
    usage: /pay <player> <amount>
    permission: rediseconomy.pay
  balance:
    description: Show balances
    usage: /balance <player>
    aliases: [money,bal]
    permission: rediseconomy.balance
  balancetop:
    description: Show top balances
    usage: /balancetop
    aliases: [moneytop,baltop]
    permission: rediseconomy.balancetop
  transaction:
    description: Show transaction info
    usage: /transaction <player> <id> [revert]
    permission: rediseconomy.admin.transaction
  browse-transactions:
    description: Show transactions
    usage: /browse-transactions <player> [timestamp]
    permission: rediseconomy.admin.browse-transactions
  last-transactions:
    description: Show last transactions
    usage: /last-transactions
    permission: rediseconomy.last-transactions
  archive-transactions:
    description: Archive transactions
    usage: /archive-transactions <file>
    permission: rediseconomy.admin.archive-transactions
  purge-balance:
    description: Purge balances
    usage: /purge-balance <player> [onlyNameUUID]
    permission: rediseconomy.admin.purge-balance
  rediseconomy:
    description: RedisEconomy commands
    usage: /rediseconomy <reload/editmessage/savemessage> [messageField] [token]
    aliases: [rediseco]
    permission: rediseconomy.admin
  switch-currency:
    description: Switch currency with another currency
    usage: /switch-currency <currency> <switch-currency>
    permission: rediseconomy.admin.switch-currency
  backup-economy:
    description: Backups and restores economy data to a file
    aliases: [restore-economy]
    usage: /backup-economy <file>
    permission: rediseconomy.admin.backup-restore
  toggle-payments:
    description: Toggles payments
    usage: /toggle-payments
    permission: rediseconomy.toggle-payments
permissions:
  rediseconomy.pay:
    description: Allows to use /pay
    default: true
  rediseconomy.payall:
    description: Allows to use /pay *
    default: false
  rediseconomy.toggle-payments:
    description: Allows to use /toggle-payments
    default: true
  rediseconomy.balance:
    description: Allows to use /balance
    default: true
  rediseconomy.balancetop:
    description: Allows to use /balancetop
    default: true
  rediseconomy.last-transactions:
    description: Allows to use /last-transactions
    default: true
  rediseconomy.admin:
    description: Allows to use admin commands
    default: op
  rediseconomy.admin.backup-restore:
    description: Allows to use /backup-economy and /restore-economy
    default: false
  rediseconomy.admin.archive-transactions:
    description: Allows to archive transactions
    default: false
  rediseconomy.admin.editmessage:
    description: Allows to use /rediseconomy editmessage
    default: false
  rediseconomy.admin.browse-transactions:
    description: Allows to browse transactions
    default: false
  rediseconomy.admin.switch-currency:
    description: Allows to switch currency
    default: false
  rediseconomy.admin.purge-balance:
    description: Allows to purge balances
    default: false
  rediseconomy.admin.transaction:
    description: Allows to use /transaction
    default: false
  rediseconomy.admin.expandpool:
    description: Allows to expand the pool
    default: false
  rediseconomy.pay.*:
    description: Allows to use /pay all currencies
    default: op
    children:
      rediseconomy.payall: true
  rediseconomy.balance.*:
    description: Allows to use /balance with other currencies
    default: op
  rediseconomy.admin.*:
    description: Allows to use all admin commands
    default: op
    children:
      rediseconomy.admin.transaction: true
      rediseconomy.admin.purge-balance: true
      rediseconomy.admin.switch-currency: true
      rediseconomy.admin.browse-transactions: true
      rediseconomy.admin.editmessage: true
      rediseconomy.admin.backup-restore: true
      rediseconomy.admin.archive-transactions: true
      rediseconomy.admin.expandpool: true
      rediseconomy.admin.test: true
